[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312']

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = ["C0111", "C0103"]

[tool.isort]
profile = "black"
line_length = 120

[tool.autopep8]
max_line_length = 120
